In [45]:
import feather
import pandas as pd

In [46]:
WCC_PATH = "../data/weakly_connected_enrollments.fthr"
FULL_PATH = "../data/merged_data.fthr"

In [47]:
# 784k rows
wcc_df = pd.read_feather(WCC_PATH)
wcc_df

,acad_career,strm,class_nbr,stdnt_enrl_status,unt_taken,unt_prgrss,grading_basis_dt,unt_billing,grading_scheme_enr,crse_grade_off,...,effdt,major1,major2,major3,major4,major5,major6,major7,sex,course_name
0,UG,1182.0,9732.0,E,5.0,5.0,2017-09-21,5.0,REG,A,...,None,None,None,None,None,None,None,None,M,MATH 51
1,UG,1182.0,16452.0,E,0.0,0.0,2017-09-21,0.0,REG,None,...,None,None,None,None,None,None,None,None,M,CHEM 31X
2,UG,1182.0,16900.0,E,5.0,5.0,2017-09-21,5.0,REG,A,...,None,None,None,None,None,None,None,None,M,CHEM 31X
3,UG,1182.0,30045.0,E,0.0,0.0,2017-09-21,0.0,REG,None,...,None,None,None,None,None,None,None,None,M,MATH 51
4,UG,1184.0,3569.0,E,5.0,5.0,2017-10-29,5.0,REG,A,...,None,None,None,None,None,None,None,None,M,CS 106X
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
784353,UG,1204.0,9902.0,E,5.0,5.0,2019-12-16,5.0,REG,None,...,None,None,None,None,None,None,None,None,F,CHEM 31B
784354,UG,1204.0,13748.0,E,0.0,0.0,2019-12-16,0.0,REG,None,...,None,None,None,None,None,None,None,None,F,CHEM 31B
784355,UG,1198.0,14272.0,E,5.0,5.0,2019-06-22,5.0,REG,CR,...,None,None,None,None,None,None,None,None,F,CS 106B
784356,UG,1198.0,15168.0,E,3.0,3.0,2019-04-17,3.0,REG,CR,...,None,None,None,None,None,None,None,None,F,CS 193C
784357,UG,1198.0,15207.0,E,3.0,3.0,2019-07-08,3.0,REG,B,...,2019-09-01,GR-SV,UGNM-SV,None,None,None,None,None,F,MS&E 260

In [48]:
# for reference, full is 2.67m rows
full_df = pd.read_feather(FULL_PATH)
full_df

,acad_career,strm,class_nbr,stdnt_enrl_status,unt_taken,unt_prgrss,grading_basis_dt,unt_billing,grading_scheme_enr,crse_grade_off,...,crse_id,effdt,major1,major2,major3,major4,major5,major6,major7,sex
0,UG,1182.0,9732.0,E,5.0,5.0,2017-09-21,5.0,REG,A,...,117257.0,None,None,None,None,None,None,None,None,M
1,UG,1182.0,16452.0,E,0.0,0.0,2017-09-21,0.0,REG,None,...,112246.0,None,None,None,None,None,None,None,None,M
2,UG,1182.0,16900.0,E,5.0,5.0,2017-09-21,5.0,REG,A,...,112246.0,None,None,None,None,None,None,None,None,M
3,UG,1182.0,19667.0,E,4.0,4.0,2017-09-21,4.0,REG,A-,...,140838.0,None,None,None,None,None,None,None,None,M
4,UG,1182.0,30045.0,E,0.0,0.0,2017-09-21,0.0,REG,None,...,117257.0,None,None,None,None,None,None,None,None,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2667926,UG,1204.0,17299.0,E,2.0,2.0,2020-01-01,2.0,REG,None,...,213977.0,None,None,None,None,None,None,None,None,F
2667927,UG,1204.0,19004.0,E,1.0,1.0,2019-12-16,1.0,REG,None,...,213806.0,None,None,None,None,None,None,None,None,F
2667928,UG,1204.0,19058.0,E,1.0,1.0,2020-01-01,1.0,REG,None,...,212709.0,None,None,None,None,None,None,None,None,F
2667929,UG,1204.0,19594.0,E,3.0,3.0,2019-11-18,3.0,REG,None,...,220870.0,None,None,None,None,None,None,None,None,F
2667930,UG,1204.0,31595.0,E,3.0,3.0,2019-12-05,3.0,REG,None,...,220779.0,None,None,None,None,None,None,None,None,F

In [49]:
# full dataset has 1136 courses
len(set(wcc_df["course_name"]))

1136

In [50]:
wcc_df["strm"] % 10 == 8

0         False
1         False
2         False
3         False
4         False
          ...
784353    False
784354    False
784355     True
784356     True
784357     True
Name: strm, Length: 784358, dtype: bool

In [51]:
# drop anything before 1162 (2015-2016 Autumn)
wcc_df.drop(wcc_df[wcc_df["strm"] < 1162].index, inplace=True)
wcc_df

,acad_career,strm,class_nbr,stdnt_enrl_status,unt_taken,unt_prgrss,grading_basis_dt,unt_billing,grading_scheme_enr,crse_grade_off,...,effdt,major1,major2,major3,major4,major5,major6,major7,sex,course_name
0,UG,1182.0,9732.0,E,5.0,5.0,2017-09-21,5.0,REG,A,...,None,None,None,None,None,None,None,None,M,MATH 51
1,UG,1182.0,16452.0,E,0.0,0.0,2017-09-21,0.0,REG,None,...,None,None,None,None,None,None,None,None,M,CHEM 31X
2,UG,1182.0,16900.0,E,5.0,5.0,2017-09-21,5.0,REG,A,...,None,None,None,None,None,None,None,None,M,CHEM 31X
3,UG,1182.0,30045.0,E,0.0,0.0,2017-09-21,0.0,REG,None,...,None,None,None,None,None,None,None,None,M,MATH 51
4,UG,1184.0,3569.0,E,5.0,5.0,2017-10-29,5.0,REG,A,...,None,None,None,None,None,None,None,None,M,CS 106X
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
784353,UG,1204.0,9902.0,E,5.0,5.0,2019-12-16,5.0,REG,None,...,None,None,None,None,None,None,None,None,F,CHEM 31B
784354,UG,1204.0,13748.0,E,0.0,0.0,2019-12-16,0.0,REG,None,...,None,None,None,None,None,None,None,None,F,CHEM 31B
784355,UG,1198.0,14272.0,E,5.0,5.0,2019-06-22,5.0,REG,CR,...,None,None,None,None,None,None,None,None,F,CS 106B
784356,UG,1198.0,15168.0,E,3.0,3.0,2019-04-17,3.0,REG,CR,...,None,None,None,None,None,None,None,None,F,CS 193C
784357,UG,1198.0,15207.0,E,3.0,3.0,2019-07-08,3.0,REG,B,...,2019-09-01,GR-SV,UGNM-SV,None,None,None,None,None,F,MS&E 260

In [52]:
# drop summer rows
wcc_df.drop(wcc_df[wcc_df["strm"] % 10 == 8].index, inplace=True)
wcc_df

,acad_career,strm,class_nbr,stdnt_enrl_status,unt_taken,unt_prgrss,grading_basis_dt,unt_billing,grading_scheme_enr,crse_grade_off,...,effdt,major1,major2,major3,major4,major5,major6,major7,sex,course_name
0,UG,1182.0,9732.0,E,5.0,5.0,2017-09-21,5.0,REG,A,...,None,None,None,None,None,None,None,None,M,MATH 51
1,UG,1182.0,16452.0,E,0.0,0.0,2017-09-21,0.0,REG,None,...,None,None,None,None,None,None,None,None,M,CHEM 31X
2,UG,1182.0,16900.0,E,5.0,5.0,2017-09-21,5.0,REG,A,...,None,None,None,None,None,None,None,None,M,CHEM 31X
3,UG,1182.0,30045.0,E,0.0,0.0,2017-09-21,0.0,REG,None,...,None,None,None,None,None,None,None,None,M,MATH 51
4,UG,1184.0,3569.0,E,5.0,5.0,2017-10-29,5.0,REG,A,...,None,None,None,None,None,None,None,None,M,CS 106X
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
784350,UG,1202.0,9597.0,E,5.0,5.0,2019-09-19,5.0,REG,B,...,None,None,None,None,None,None,None,None,F,CHEM 31A
784351,UG,1202.0,9617.0,E,0.0,0.0,2019-09-19,0.0,REG,None,...,None,None,None,None,None,None,None,None,F,CHEM 31A
784352,UG,1204.0,9459.0,E,5.0,5.0,2019-10-27,5.0,REG,None,...,None,None,None,None,None,None,None,None,F,PSYCH 1
784353,UG,1204.0,9902.0,E,5.0,5.0,2019-12-16,5.0,REG,None,...,None,None,None,None,None,None,None,None,F,CHEM 31B
784354,UG,1204.0,13748.0,E,0.0,0.0,2019-12-16,0.0,REG,None,...,None,None,None,None,None,None,None,None,F,CHEM 31B

In [53]:
len(set(wcc_df["course_name"]))

966

### WCC dataset has 966 unique courses, 223749 rows.